apiVersion: v1
kind: Service
metadata:
  name: dockerhub-test-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: dockerhub-test-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
